version: '3'

networks:
  cursosnetwork:
    driver: bridge

volumes:
  nexus-data:
  jenkins-data:
  db-data:
  jar-data:

services:
  nexus:
    image: sonatype/nexus
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - 8081:8081
    networks:
      - cursosnetwork

    container_name: nexus
  sonarqube:
    image: sonarqube
    networks:
      - cursosnetwork
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube

  jenkins:
    image: jenkins
    networks:
      - cursosnetwork
    privileged: true
    user: root
    ports:
      - 8082:8080
      - 50000:50000
    container_name: cursos-jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.soc
      - "jenkins-data:/var/jenkins_home"
      - "jar-data:/var/jar"
    depends_on:
      - sonarqube

  mysql:
     image: mysql
     container_name: cursos-mysql
     privileged: true
     volumes:
       - "db-data:/var/lib/mysql"
     ports:
       - 3306:3306
       - 33060:33060
     restart: always
     networks:
       - cursosnetwork
     environment:
       MYSQL_ROOT_PASSWORD: pass

  spring-boot:
    build: .
    entrypoint: sh -c './wait-for cursos2018.jar'
    ports:
      - 8090:8080
    restart: always
    volumes:
      - "jar-data:/var/jar"
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
    networks: 
      - cursosnetwork 

    
